FROM node:22-alpine

# Cài full toolchain cho Development
RUN apk add --no-cache python3 make g++ git openssl libc6-compat vips-dev

WORKDIR /app

ENV NODE_ENV=development

# Script entrypoint
COPY infra/scripts/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8080 9229

# Không dùng ENTRYPOINT cứng, để Docker Compose có thể override command nếu cần
CMD ["/entrypoint.sh"]