FROM node:22.15-alpine

WORKDIR /app

# 1. Cài đặt thư viện hệ thống (Giữ nguyên vì Alpine cần C++ compiler)
RUN apk add --no-cache \
    build-base gcc g++ autoconf automake zlib-dev libtool \
    python3 make nasm vips-dev git linux-headers procps

# 2. KÍCH HOẠT PNPM
RUN corepack enable && corepack prepare pnpm@latest --activate

# 3. Copy file config và lockfile của pnpm
COPY package.json pnpm-lock.yaml* ./

# 4. Cài đặt dependencies bằng pnpm
RUN pnpm install --frozen-lockfile

# 5. Copy toàn bộ source code
COPY . .

ENV NODE_ENV=development

# Setup entrypoint
COPY infra/scripts/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 8080 9229

CMD ["/entrypoint.sh"]
